### ISSUE TITLE
Fetching 120 files from cache seems slower than it should

### ISSUE THREAD

**Issue by fasterthanlime** [electron/electron-compile#224]
It might be that I'm just thick, but when changing the contents of a source file that's imported exactly once (by one React component), it appears like electron-compile removes *all the app's modules* from the cache and recompiles them all.

Is that the intended behavior or am I being a big dummy?

---

That's with typescript, here's my compilerc:

```javascript
{
  "application/javascript": {
    "passthrough": true
  },
  "text/typescript": {
    "target": "es2017",
    "lib": ["dom", "dom.iterable", "scripthost", "es6"],
    "module": "commonjs",
    "noImplicitAny": true,
    "experimentalDecorators": true,
    "noUnusedLocals": true,
    "sourceMap": true,
    "jsx": "react",
    "noEmitOnError": true
  }
}
```

here's my init.js:

```javascript
const path = require("path");
const appRoot = path.resolve(path.join(__dirname, ".."));
require("electron-compile-ftl").init(appRoot, require.resolve("./main"));
```

electron-compile @ 6.4.0 and electron-compilers @ 5.8.0, windows 10, electron 1.6.2

---

Note: I've done a bit of research on react-hot-loader@next's side, and it seems that this could be caused by the store being required in `main.js` instead of the top-level component. I've tried requiring it only in the to-level component instead but then it all went crazy (probably on account of it being a store sync'd by IPC, ie. [redux-electron-store](https://github.com/samiskin/redux-electron-store)).

**Comment by paulcbetts** [comment]
HMR is v slow at the moment because of the way we walk the AST, it's on my TODO to improve this, but since it doesn't affect production build I pushed it down a bit

**Comment by fasterthanlime** [comment]
Cool! Let me know if I can help in any way, I don't mind hacking on electron-compile{,rs} some, since it saves me all the headache of dealing with webpack :)

**Comment by paulcbetts** [comment]
@fasterthanlime If you want to have a hack at it, https://github.com/electron/electron-compilers/blob/master/src/js/typescript.js#L104 is the problematic code - while it's super Correct:tm:, finding the exports this way is slow. as. fuck. Basically, we just need to write a function to find all the named exports out of a single Typescript file, we don't actually need to check or understand types

**Comment by fasterthanlime** [comment]
Oh wow, you weren't kidding

![exports](https://cloud.githubusercontent.com/assets/7998310/25453956/1b6f4ace-2acb-11e7-82ae-ff7be8d0f452.png)

**Comment by fasterthanlime** [comment]
Opened PR for the "get rid of typecheck" thingy, but I'm still seeing my original problem, here's a chrome devtools log: https://gist.github.com/fasterthanlime/d1d71ab1db6934fcfcc81d5215d2b31c

I've only touched `hub-sidebar.tsx`, I would expect only it to get recompiled (or maybe the 2-3 modules that actually require it, since the compiler has no way of telling us none of the exports have actually changed).

Are Typescript Compiler Services an option at some point? Seems like we can "increment version numbers" when we detect a timestamp change and the tsc mammoth would do the minimum amount of right things™️ - not sure how that'd play out in the general electron-compilers infrastructure though.

**Comment by paulcbetts** [comment]
@fasterthanlime Lemme try it on Trickline and see if I get the right behavior

**Comment by paulcbetts** [comment]
@fasterthanlime I'm not seeing the compiler invoked more than once for a changed file (Cmd-O in Sources => "Typescript.ts" => set a breakpoint on CompileSync, then save a file in your editor). Could your editor maybe be changing >1 file at a time?

**Comment by fasterthanlime** [comment]
Hmmm, reading the log more closely:

  * There's 121 "Removing node module entry for X"
  * There's 121 "Compiling X"
  * There's 1 "Invalidating cache entry"

So there's 121 files on electron-compile's radar, and the typescript compiler indeed only runs on one, but each cache fetch seems to take a while (typically 2+4+2ms - at 8ms per file, that adds up to 968ms).

Any particular reason the `realpathCache` [has a size of 32](https://github.com/electron/electron-compile/blob/14fe00cbf2bae5f621878099cb24cc83de04aee6/src/sanitize-paths.js#L5) ? Could that be part of why it's slower than expected?

**Comment by paulcbetts** [comment]
@fasterthanlime I have no idea why I set that number so low, let's bump that shit ⬆️

**Comment by paulcbetts** [comment]
6.4.1 now sets this cache size to 1024 ✨
